version: "3"
services:
  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=hosiptal_db
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234
  server:
    image: hospitalmanagement
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/hosiptal_db?useSSL=false",
        "spring.datasource.username": "sa",
        "spring.datasource.password": "1234",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "create"
      }'

    networks:
      - springmysql-net
    depends_on:
      - mysqldb

networks:
  springmysql-net: